[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[programs.devnet]
puppet = "DBfnXvvaR46XSuwKK9Uyg5SdW3WNZtJhA6BizDQSym6J"
puppet_master = "3kyC6H6Q6s7dQYwYyEBGLptFcqLNtpVPVeGmBubhtuN5"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
# test = "yarn run mocha -t 1000000 tests/"
